# Generated by Django 5.1.6 on 2025-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('plural', models.CharField(max_length=150, verbose_name='Plural name')),
                ('latin_name', models.CharField(max_length=150, verbose_name='Latin name')),
                ('category', models.CharField(max_length=3, verbose_name='Category')),
                ('rarity', models.CharField(max_length=15, verbose_name='Rarity')),
            ],
        ),
    ]
