# Generated by Django 5.1.6 on 2025-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Latin name'),
        ),
    ]
