# Generated by Django 5.1.6 on 2025-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_species_latin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
    ]
