# Generated by Django 5.1.6 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Imported'),
        ),
    ]
