# Generated by Django 5.1.6 on 2025-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_observation_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
